# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20170220_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomation_details',
            name='message_content',
            field=models.TextField(verbose_name='MESSAGE'),
        ),
    ]
