# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20170220_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomation_details',
            old_name='eamil',
            new_name='eamil_address',
        ),
    ]
