# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20170220_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infomation_dars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('eamil_address', models.CharField(max_length=50, verbose_name='Email')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('message_content', models.TextField(verbose_name='MESSAGE')),
            ],
        ),
        migrations.CreateModel(
            name='Infomation_szqt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('eamil_address', models.CharField(max_length=50, verbose_name='Email')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('message_content', models.TextField(verbose_name='MESSAGE')),
            ],
        ),
        migrations.DeleteModel(
            name='Infomation_details',
        ),
    ]
